project:
  type: website

website:
  title: "Walter Mangione"
  page-footer:
    right: "© 2025 Walter Mangione Università degli Studi di Bari Aldo Moro"
  navbar:
    left: []   # no items on left
    right: []  # no items on right, search will appear automatically

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toggle: true     # enables theme toggle
    toc: true
    toc-depth: 3
    code-link: true
    search: true     # enables search bar
