project:
  type: website

output-dir: docs

website:
  title: "Walter Mangione"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Contacts"
        href: index.qmd#contacts

format:
  html:
    theme: darkly
    css: styles.css