project:
  type: website

output-dir: docs

website:
  title: "Walter Mangione"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Research"
        href: research.qmd
      - text: "Contacts"
        href: contacts.qmd
format:
  html:
    theme: darkly
    css: styles.css
    include-in-header: header.html

